#!/bin/zsh

ensure_dependency() {
  type $1 >/dev/null 2>&1 || {
    echo >&2 "I require '$1' but it's not installed.  Aborting."
    exit 1
  }
}

install_bin_on_cli() {
  local DIR="${0:A:h}"
  local LINE="export PATH=\"$DIR/bin:\$PATH\""

  PROFILE=~/.zprofile
  grep -qsFx "$LINE" "$PROFILE" || echo "\n$LINE\n" >>"$PROFILE"
}
